In [1]:
import numpy as np

In [4]:
a = np.array([[1,11,111],[2,22,222],[3,33,333],[4,44,444]])
b = np.array([[5,55,555], [6,66,666]])

In [5]:
a

array([[  1,  11, 111],
       [  2,  22, 222],
       [  3,  33, 333],
       [  4,  44, 444]])

In [6]:
b

array([[  5,  55, 555],
       [  6,  66, 666]])

In [7]:
np.concatenate((a, b), axis=0)

array([[  1,  11, 111],
       [  2,  22, 222],
       [  3,  33, 333],
       [  4,  44, 444],
       [  5,  55, 555],
       [  6,  66, 666]])